- name: importing app-setup yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: importing go-setup yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: go-setup

- name: importing systemd yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml
