- name: importing app-setup yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: importing nodejs yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: importing mongodb-setup yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup
- name: importing systemd yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
- name: importing systemd yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: deployment
