- name: installing nginx server
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: Deleting nginx html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: creating Html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: downloading the application zip
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp
- name: unzipping the web
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# - name: configuring reverse proxy
#   ansible.builtin.copy:
#     src: roboshop.conf
#     dest: /etc/nginx/default.d/roboshop.conf

- name: configuring reverse proxy
  ansible.builtin.template:
    src: roboshop.conf.j2
    dest: /etc/nginx/default.d/roboshop.conf
  notify:
    - Restart nginx
# - name: start and enable nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted
#     enabled: yes
