- name: copying mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: installing mongodb
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get products count
  ansible.builtin.shell: mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"

- name: get users count
  ansible.builtin.command: mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: component == "user"

- name: print the product count
  ansible.builtin.debug:
    msg: " Product count {{products_count}}"

- name: print the user count
  ansible.builtin.debug:
    msg: " Product count {{user_count}}"

- name: "Load catalogue data into mongodb"
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: component == "catalogue" and products_count.stdout == "0"
  #ignore_errors: true

- name: "Load user data into mongodb"
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: component == "user" and user_count.stdout == "0"
  #ignore_errors: true
