- name: importing common yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: importing common yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: importing common yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml
